version: 2
jobs:
  deploy:
    docker:
      - image: google/cloud-sdk
    environment:
      PROJECT_NAME: "cf-deploy"
      GOOGLE_PROJECT_ID: "pantheon-lighthouse-poc"
      FUNCTION_NAME: "cf-deploy"
      ENTRYPOINT: "FnDeployCI"
      BUCKNAME: "cf-deploy-lh"
      
    steps:
      - checkout
      - run:
          name: Authorize GCloud Command Line Tool
          command: |
            echo ${GCLOUD_SERVICE_KEY} > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
      - run:
         name: Install libzip-dev
         command: |
          apt-get install -y libzip-dev
          apt-get install -y zip
      - run:
         name: Creating function zip file
         command: |
          zip --filesync -r9 ${PROJECT_NAME}.zip .
      - run:
         name: Upload zip file to GCS
         command: |
          gsutil cp ${PROJECT_NAME}.zip gs://${BUCKNAME}/${PROJECT_NAME}.zip      
      - run:
          name: Deploy To Google Cloud Functions        
          command: |
            # Deploy command
            gcloud functions deploy "${FUNCTION_NAME}" \
              --runtime=go116 \
              --region=us-central1 \
              --source="gs://${BUCKNAME}/${PROJECT_NAME}.zip" \
              --entry-point "${ENTRYPOINT}" \
              --trigger-http \
              --project "${GOOGLE_PROJECT_ID}" \
              --allow-unauthenticated

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - main