version: 2
jobs:
  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run:
          name: Authorize GCloud Command Line Tool
          command: |
            echo ${GCLOUD_SERVICE_KEY} > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
      - run:
          name: Deploy To Google Cloud Functions
          command: |
            # Variables
            FUNCTION_NAME=cf-deploy-circleci
            ENTRYPOINT=FnDeployCI
            GCP_PROJECT=pantheon-lighthouse-poc
            # Deploy command
            gcloud functions deploy $FUNCTION_NAME \
              --gen2 \
              --runtime=go116 \
              --region=us-central1 \
              --source=. \
              --entry-point $ENTRYPOINT \
              --trigger-http \
              --project $GCP_PROJECT \
              --allow-unauthenticated

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - main